name: Run Tests on PR

on:
  workflow_dispatch:
  push:
    branches: [users/db/create-delete-users]

env:
  NPM_AUTHTOKEN: ${{ secrets.NPM_AUTHTOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  API_KEY: ${{ secrets.API_KEY }}
  APP_ID: ${{ secrets.APP_ID }}
  APP_TOKEN: ${{ secrets.APP_TOKEN }}
  EXAMPLE_USER_ID: ${{ secrets.EXAMPLE_USER_ID }}
  PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}

jobs:
  publish:
    name: Run Tests on PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unit Test
        run: npm i && npm run test
