name: Publish to NPM Registry

on:
  push:
    branches: [main]

env:
  NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
  PAT: ${{ secrets.BEACHBALL_PAT }}

jobs:
  publish:
    name: Publish to NPM Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ env.PAT }}

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build:prod

      - name: Beachball Check
        run: |
          npm run beachball-check

      - name: Deploy to NPM
        run: |
          git config user.email "beachball_bot@passage.id"
          git config user.name "Beachball Machine Account"
          git remote set-url origin https://$GITHUB_ACTOR:$PAT@github.com/$GITHUB_REPOSITORY.git
          npm run publish ${{ env.NPM_ACCESS_TOKEN }}
